- apiVersion: v1beta1
  kind: Agent
  metadata:
    name: Alarm
  spec:
    credentials:
      username: '111111'
      secret: 'changeit'
    domains: [sip.local]

- apiVersion: v1beta1
  kind: Agent
  metadata:
    name: Alarm Receiver
  spec:
    credentials:
      username: 'arc'
      secret: 'changeit'
    domains: [sip.local]
