{{- if eq .Values.adminService.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm2.fullname" . }}-{{ .Values.adminService.name }}
  labels:
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.adminService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  {{- if .Values.adminService.externalIPs }}
  externalIPs: 
  {{- range .Values.adminService.externalIPs }}
    - {{.}}
  {{- end }}
  {{- end }}
  type: {{ .Values.adminService.type }}
  ports:
  - name: {{ .Values.adminService.name }}
    port: {{ .Values.adminService.port }}
    targetPort: {{ .Values.adminService.containerPort | default .Values.adminService.port }}
  selector:
    {{- include ".helm2.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if eq .Values.udpSignalingService.enabled true }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include ".helm2.fullname" . }}-{{ .Values.udpSignalingService.name }}
  labels:
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.udpSignalingService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  {{- if .Values.udpSignalingService.externalIPs }}
  externalIPs: 
  {{- range .Values.udpSignalingService.externalIPs }}
    - {{.}}
  {{- end }}
  {{- end }}
  type: {{ .Values.udpSignalingService.type }}
  {{- if ne .Values.udpSignalingService.type "ClusterIP" }}
  externalTrafficPolicy: {{ .Values.udpSignalingService.externalTrafficPolicy }}
  {{- end}}
  ports:
  - name: {{ .Values.udpSignalingService.name }}
    port: {{ .Values.udpSignalingService.port }}
    protocol: UDP
  selector:
    {{- include ".helm2.selectorLabels" . | nindent 4 }}
{{- end }}
