apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include ".helm2.fullname" . }}
  labels:
    {{- include ".helm2.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include ".helm2.selectorLabels" . | nindent 6 }}
  serviceName: "scaipproxy"      
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include ".helm2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: scaipproxy
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          exec:
            command:
            - curl
            - -k
            - --fail
            - --silent
            - --show-error
            - --connect-timeout
            - "2"
            - -L
            - https://localhost:4567/api/v1beta1/system/status
          initialDelaySeconds: {{ .Values.scaipproxy.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.scaipproxy.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.scaipproxy.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.scaipproxy.livenessProbe.failureThreshold }}        
        env:
        - name: DATA_SOURCE_PROVIDER
          value: redis_data_provider
        - name: DATA_SOURCE_PARAMETERS
          value: host={{ .Release.Name }}-redis-master,port=6379
        - name: EXTERN_ADDR
          value: {{ .Values.scaipproxy.externAddr | quote }}
        - name: LOCALNETS
          value: {{ join "," .Values.scaipproxy.localnets }}
        - name: JAVA_OPTS
          value: {{ .Values.scaipproxy.javaOpts | quote }}          
        - name: DIGEST_AUTH_ADDR
          value: {{ join "," .Values.scaipproxy.digestAuthAddr }}
        - name: USER_AGENT
          value: {{ .Values.scaipproxy.userAgent | quote }}
        - name: BIND_ADDR
          value: {{ .Values.scaipproxy.bindAddr | quote }}
        - name: RECORD_ROUTE
          value: {{ .Values.scaipproxy.recordRoute | quote }}
        - name: USE_TO_AS_AOR
          value: {{ .Values.scaipproxy.useToAsAOR | quote }}
        - name: PATCH_REQUEST_URI
          value: {{ .Values.scaipproxy.patchRequestURI | quote }}
        - name: REGISTRAR_INTF
          value: {{ .Values.scaipproxy.registrarIntf | quote }}
        - name: ACCESS_CONTROL_LIST_ALLOW
          value: {{ join "," .Values.scaipproxy.accessControlList.allow }}
        - name: ACCESS_CONTROL_LIST_DENY
          value: {{ join "," .Values.scaipproxy.accessControlList.deny }}
        - name: REST_SERVICE_BIND_ADDR
          value: {{ .Values.scaipproxy.restService.bindAddr | quote }}
        - name: REST_SERVICE_PORT
          value: {{ .Values.scaipproxy.restService.port | quote }}
        - name: REST_SERVICE_MIN_THREADS
          value: {{ .Values.scaipproxy.restService.minThreads | quote }}
        - name: REST_SERVICE_MAX_THREADS
          value: {{ .Values.scaipproxy.restService.maxThreads | quote }}
        - name: REST_SERVICE_TIMEOUT_MILLIS
          value: {{ .Values.scaipproxy.restService.timeoutMillis | quote }}
        - name: REST_SERVICE_UNSECURED
          value: {{ .Values.scaipproxy.restService.unsecured | quote }}
        - name: REST_SERVICE_KEY_STORE
          value: {{ .Values.scaipproxy.restService.keyStore | quote }}
        - name: REST_SERVICE_KEY_STORE_PASSWORD
          value: {{ .Values.scaipproxy.restService.keyStorePassword | quote }}
        - name: REST_SERVICE_TRUST_STORE
          value: {{ .Values.scaipproxy.restService.trustStore | quote }}
        - name: REST_SERVICE_TRUST_STORE_PASSWORD
          value: {{ .Values.scaipproxy.restService.trustStorePassword | quote }}
        - name: SECURITY_CONTEXT_KEY_STORE
          value: {{ .Values.scaipproxy.securityContext.keyStore | quote }}
        - name: SECURITY_CONTEXT_TRUST_STORE
          value: {{ .Values.scaipproxy.securityContext.trustStore | quote }}
        - name: SECURITY_CONTEXT_KEY_STORE_PASSWORD
          value: {{ .Values.scaipproxy.securityContext.keyStorePassword | quote }}
        - name: SECURITY_CONTEXT_DEBUGGING
          value: {{ .Values.scaipproxy.securityContext.debugging | quote }}
        - name: SECURITY_CONTEXT_CLIENT_KEY_STORE_TYPE
          value: {{ .Values.scaipproxy.securityContext.client.keyStoreType | quote }}
        - name: SECURITY_CONTEXT_CLIENT_PROTOCOLS
          value: {{ join "," .Values.scaipproxy.securityContext.client.protocols }}
        ports:
        - name: {{ .Values.adminService.name }}
          containerPort: {{ .Values.adminService.containerPort | default .Values.adminService.port }}
          protocol: TCP
        {{- if eq .Values.udpSignalingService.enabled true }}
        - name: {{ .Values.udpSignalingService.name }}
          containerPort: {{ .Values.udpSignalingService.containerPort | default .Values.udpSignalingService.port }}
          protocol: UDP
        {{- end }}
        volumeMounts:
        - name: log4j2
          mountPath: /opt/scaipproxy/config/log4j2.yml
          subPath: log4j2.yml
        {{- if eq .Values.certs.provided true }}  
        - name: domains-cert
          mountPath: /opt/scaipproxy/etc/certs/domains-cert.jks
          subPath: domains-cert.jks
          readOnly: true
        - name: api-cert
          mountPath: /opt/scaipproxy/etc/certs/api-cert.jks
          subPath: api-cert.jks
          readOnly: true
        {{- end }}
        {{- if eq .Values.applicationinsights.enabled true }} 
        - name: applicationinsights
          mountPath: /opt/scaipproxy/libs/applicationinsights.json
          subPath: applicationinsights.json
          readOnly: true
        {{- end }}        
        resources:
          {{- if .Values.resources.limits }}
          limits:
          {{- .Values.resources.limits | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.resources.requests }}
          requests:
          {{- .Values.resources.requests | toYaml | nindent 12 }}
          {{- end }}
      volumes:
      - name: log4j2
        configMap:
          name: {{ include ".helm2.fullname" . }}-log4j2
      {{- if eq .Values.certs.provided true }}          
      - name: domains-cert
        secret:
          secretName: {{ .Values.certs.name }}
      - name: api-cert
        secret:
          secretName: {{ .Values.certs.name }}
      {{- end }}
      {{- if eq .Values.applicationinsights.enabled true }}
      - name: applicationinsights
        secret:
          secretName: {{ .Values.applicationinsights.name }}
      {{- end }}
