# Server's image repo and pull policy
# We recommend using 'Always'
image:
  repository: fonoster/scaipproxy
  pullPolicy: Always
  tag: ""

# Enable to use obtain remote access to the
# server via `rctl` or the restful api.
#
# The service type defaults to ClusterIP allowing you
# to use Ingress. But you could replace with other service type
adminService:
  enabled: true
  name: api
  type: ClusterIP
  port: 4567
  annotations: {}
  externalIPs: []

# Use this service to enable UDP access to the server's signaling
# capabilities. Keep in mind that this will create the service for you
# But the UDP protocol must also be enabled(default) in the server.
udpSignalingService:
  enabled: true
  externalTrafficPolicy: Local
  name: sipudp
  type: ClusterIP
  port: 5060
  annotations: {}
  externalIPs: []

# Certificates Management
certs:
  provided: false
  name: scaipproxy-cert

# Azure ApplicationInsights Configuration
applicationinsights:
  enabled: false
  name: scaipproxy-applicationinsights

# Server Configuration
scaipproxy:
  userAgent: "SCAIPProxy"
  bindAddr: ""
  externAddr: ""
  localnets: []
  recordRoute: false
  useToAsAOR: false
  patchRequestURI: false
  registrarIntf: External
  javaOpts: ""
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 5
    successThreshold: 1
    failureThreshold: 3  
  accessControlList:
    deny: []
    allow: []
  restService:
    bindAddr: 0.0.0.0
    port: 4567
    minThreads: 8
    maxThreads: 200
    timeoutMillis: 5000
    unsecured: false
    keyStore: ""
    trustStore: ""
    keyStorePassword: ""
    trustStorePassword: ""
  securityContext:
    keyStore: ""
    trustStore: ""
    keyStorePassword: ""
    debugging: false
    client:
      keyStoreType: jks
      protocols: [TLSv1.2,TLSv1.1,TLSv1]
  logLevel: info

redis:
  usePassword: false
  cluster:
    enabled: false
  persistence:
    enabled: true
    mountPath: /bitnami/redis
    size: 5Gi

replicaCount: 1
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources:
  limits: {}
  requests: {}
nodeSelector: {}
tolerations: []
affinity: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
